-- MySQL Script generated by MySQL Workbench
-- Thu Nov 11 16:11:10 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema invsys
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema invsys
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `invsys` DEFAULT CHARACTER SET utf8 ;
USE `invsys` ;

-- -----------------------------------------------------
-- Table `invsys`.`Itemgroups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `invsys`.`Itemgroups` (
  `idItemgroup` INT NOT NULL,
  `Name` VARCHAR(25) NOT NULL,
  `Description` VARCHAR(70) NULL,
  PRIMARY KEY (`idItemgroup`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invsys`.` Itemtypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `invsys`.` Itemtypes` (
  `id Itemtype` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(80) NULL,
  `fk_idItemgroup` INT NOT NULL,
  PRIMARY KEY (`id Itemtype`),
  INDEX `idItemgroup_idx` (`fk_idItemgroup` ASC) VISIBLE,
  CONSTRAINT `idItemgroup_of_itemtype`
    FOREIGN KEY (`fk_idItemgroup`)
    REFERENCES `invsys`.`Itemgroups` (`idItemgroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invsys`.`Subitemtypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `invsys`.`Subitemtypes` (
  `idSubitemtype` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(70) NULL,
  `fk_idItemtype` INT NOT NULL,
  PRIMARY KEY (`idSubitemtype`),
  INDEX `idItemtype_idx` (`fk_idItemtype` ASC) VISIBLE,
  CONSTRAINT `idItemtype_of_subitemtype`
    FOREIGN KEY (`fk_idItemtype`)
    REFERENCES `invsys`.` Itemtypes` (`id Itemtype`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invsys`.`Sectors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `invsys`.`Sectors` (
  `idSector` INT NOT NULL,
  `Name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idSector`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invsys`.`Brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `invsys`.`Brands` (
  `idBrand` INT NOT NULL,
  `Name` VARCHAR(55) NOT NULL,
  `Sector` INT NOT NULL,
  `Description` VARCHAR(75) NULL,
  PRIMARY KEY (`idBrand`),
  INDEX `idSector_idx` (`Sector` ASC) VISIBLE,
  CONSTRAINT `idSector_of_brand`
    FOREIGN KEY (`Sector`)
    REFERENCES `invsys`.`Sectors` (`idSector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invsys`.`Floors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `invsys`.`Floors` (
  `idFloor` INT NOT NULL,
  `Alias` VARCHAR(20) NULL,
  PRIMARY KEY (`idFloor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invsys`.`Locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `invsys`.`Locations` (
  `idLocation` INT NOT NULL,
  `Name` VARCHAR(30) NOT NULL,
  `Description` VARCHAR(65) NULL,
  `fk_idFloor` INT NOT NULL,
  PRIMARY KEY (`idLocation`),
  INDEX `idFloor_idx` (`fk_idFloor` ASC) VISIBLE,
  CONSTRAINT `idFloor_of_location`
    FOREIGN KEY (`fk_idFloor`)
    REFERENCES `invsys`.`Floors` (`idFloor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invsys`.`Statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `invsys`.`Statuses` (
  `idStatus` INT NOT NULL,
  `Description` VARCHAR(55) NOT NULL,
  `Critical` TINYINT(10) NOT NULL,
  PRIMARY KEY (`idStatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invsys`.`Items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `invsys`.`Items` (
  `idItem` INT NOT NULL,
  `fk_idBrand` INT NOT NULL,
  `fk_idItemtype` INT NOT NULL,
  `fk_idLocation` INT NOT NULL,
  `fk_idStatus` INT NOT NULL,
  `Model` VARCHAR(35) NULL,
  `Serial` VARCHAR(28) NULL,
  `Color` INT NULL,
  `Observations` VARCHAR(60) NULL,
  `Active` TINYINT(1) NULL,
  PRIMARY KEY (`idItem`),
  INDEX `idItemtype_idx` (`fk_idItemtype` ASC) VISIBLE,
  INDEX `idBrand_idx` (`fk_idBrand` ASC) VISIBLE,
  INDEX `idLocation_idx` (`fk_idLocation` ASC) VISIBLE,
  INDEX `idStatus_idx` (`fk_idStatus` ASC) VISIBLE,
  CONSTRAINT `idItemtype_of_item`
    FOREIGN KEY (`fk_idItemtype`)
    REFERENCES `invsys`.` Itemtypes` (`id Itemtype`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idBrand_of_item`
    FOREIGN KEY (`fk_idBrand`)
    REFERENCES `invsys`.`Brands` (`idBrand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idLocation_of_item`
    FOREIGN KEY (`fk_idLocation`)
    REFERENCES `invsys`.`Locations` (`idLocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idStatus_of_item`
    FOREIGN KEY (`fk_idStatus`)
    REFERENCES `invsys`.`Statuses` (`idStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invsys`.`Subitems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `invsys`.`Subitems` (
  `idSubitem` INT NOT NULL,
  `fk_idBrand` INT NOT NULL,
  `fk_idSubitemtype` INT NOT NULL,
  `fk_idLocation` INT NOT NULL,
  `fk_idStatus` INT NOT NULL,
  `fk_idItem` INT NULL,
  `Model` VARCHAR(35) NULL,
  `Serial` VARCHAR(28) NULL,
  `Color` INT NULL,
  `Observations` VARCHAR(60) NULL,
  `Active` TINYINT(1) NULL,
  PRIMARY KEY (`idSubitem`),
  INDEX `idBrand_idx` (`fk_idBrand` ASC) VISIBLE,
  INDEX `idLocation_idx` (`fk_idLocation` ASC) VISIBLE,
  INDEX `idItem_idx` (`fk_idItem` ASC) VISIBLE,
  INDEX `idSubitemtype_idx` (`fk_idSubitemtype` ASC) VISIBLE,
  INDEX `idStatus_idx` (`fk_idStatus` ASC) VISIBLE,
  CONSTRAINT `idBrand_of_subitem`
    FOREIGN KEY (`fk_idBrand`)
    REFERENCES `invsys`.`Brands` (`idBrand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idSubitemtype_of_subitem`
    FOREIGN KEY (`fk_idSubitemtype`)
    REFERENCES `invsys`.`Subitemtypes` (`idSubitemtype`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idLocation_of_subitem`
    FOREIGN KEY (`fk_idLocation`)
    REFERENCES `invsys`.`Locations` (`idLocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idItem_of_subitem`
    FOREIGN KEY (`fk_idItem`)
    REFERENCES `invsys`.`Items` (`idItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idStatus_of_subitem`
    FOREIGN KEY (`fk_idStatus`)
    REFERENCES `invsys`.`Statuses` (`idStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invsys`.`Changelog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `invsys`.`Changelog` (
  `idChange` INT NOT NULL,
  `fk_idItem` INT NULL,
  `fk_idSubitem` INT NULL,
  `fk_idOldStatus` INT NOT NULL,
  `Description` VARCHAR(60) NOT NULL,
  `Date` DATETIME NULL,
  PRIMARY KEY (`idChange`),
  INDEX `idItem_idx` (`fk_idItem` ASC) VISIBLE,
  INDEX `idSubitem_idx` (`fk_idSubitem` ASC) VISIBLE,
  INDEX `idOldStatus_idx` (`fk_idOldStatus` ASC) VISIBLE,
  CONSTRAINT `idItem_of_changelog`
    FOREIGN KEY (`fk_idItem`)
    REFERENCES `invsys`.`Items` (`idItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idSubitem_of_changelog`
    FOREIGN KEY (`fk_idSubitem`)
    REFERENCES `invsys`.`Subitems` (`idSubitem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idOldStatus_of_changelog`
    FOREIGN KEY (`fk_idOldStatus`)
    REFERENCES `invsys`.`Statuses` (`idStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
